stages:
  - build
  - test
  - publish

variables:
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  NPM_TOKEN: $CI_JOB_TOKEN

include:
  - project: 'hive/common-ci-configuration'
    ref: 7c58303ffb61d91ef9662ec20e7b498bc6f62b8f
    file:
      - '/templates/wasm_build.gitlab-ci.yml'

build_hb_auth:
  extends: .job-defaults
  stage: build
  image: ${EMSCRIPTEN_IMAGE}
  before_script:
    - pnpm install --frozen-lockfile
  script:
    - pnpm run build
  tags:
    - public-runner-docker
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/package.json"
      - "$CI_PROJECT_DIR/dist"
      - "$CI_PROJECT_DIR/README.md"
      - "$CI_PROJECT_DIR/api.md"
      - "$CI_PROJECT_DIR/LICENSE.md"

test_hb_auth:
  extends: .job-defaults
  needs: 
    - job: build_hb_auth
      artifacts: true
  stage: test
  script:
    - pnpm test
  tags:
    - public-runner-docker
  artifacts:
    reports:
      junit: results.xml
    paths:
      - "$CI_PROJECT_DIR/results.json"


publish_hb_auth:
  extends: .job-defaults
  stage: publish
  image: ${EMSCRIPTEN_IMAGE}
  variables:
    PUBLISH_TOKEN: "$NPM_TOKEN"
    NPM_SCOPE: "@hive"
    NPM_REGISTRY: "gitlab.syncad.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/"
  script:
    - scripts/ci-helpers/bump_npm_version.sh "$PUBLISH_TOKEN" "$NPM_SCOPE" "$NPM_REGISTRY"
    - scripts/ci-helpers/npm_publish.sh "$NPM_REGISTRY"
  needs:
    - job: test_hb_auth
    - job: build_hb_auth
      artifacts: true
  tags:
    - public-runner-docker
