stages:
  - build
  - test
  - publish

variables:
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  NPM_TOKEN: $CI_JOB_TOKEN

include:
  - project: 'hive/common-ci-configuration'
    ref: d34967496fcf2bb520426aba537dcd5048ad41b2
    file:
      - '/templates/wasm_build.gitlab-ci.yml'

build_hb_auth:
  extends: .npm_build_template
  stage: build
  variables:
    DIST_DIR: "${CI_PROJECT_DIR}/dist"
    NPM_PACKAGE_SCOPE: "@hiveio"
    NPM_PACKAGE_NAME: "hb-auth"

  tags:
    - public-runner-docker
  artifacts:
    paths:
      - "${DIST_DIR}/*.tgz"  # Built package
      - "$CI_PROJECT_DIR/package.json"
      - "$CI_PROJECT_DIR/dist"
      - "$CI_PROJECT_DIR/README.md"
      - "$CI_PROJECT_DIR/api.md"
      - "$CI_PROJECT_DIR/LICENSE.md"

test_hb_auth:
  extends: .npm_test_template
  variables:
    PACKAGE_TGZ_PATH: "${BUILT_PACKAGE_PATH}"

  needs: 
    - job: build_hb_auth
      artifacts: true
  stage: test
  tags:
    - public-runner-docker

publish_hb_auth:
  extends: .npm_deploy_package_template
  stage: publish
  variables:
    PACKAGE_TGZ_PATH: "${BUILT_PACKAGE_PATH}"
    NPM_PACKAGE_SCOPE: "@hiveio"

  needs:
    - job: test_hb_auth
    - job: build_hb_auth
      artifacts: true
  tags:
    - public-runner-docker
